### ISSUE TITLE
Empty Glucose Service last record request exception

### ISSUE THREAD

**Issue by snap40ben** [ThomasGerstenberg/blatann#145]
### Problem
Hello, there seem to be an issue in the `_on_report_records_request` function from the `GlucoseServer`: when requesting the last record while the database is empty, an exception is thrown:
```
[2023-09-27 10:13:17,323] [/dev/cu.usbmodemD3DAC88AD6C42_Event] [blatann.gatt.gatts.notify:93] [ERROR]: Error occurred while handling event 'Write Event'. Sender: Characteristic: Record Access Control Point (2a52), CharProps(w,i), attributes: [
    u
    t
    f
    8
  ], Event Args: WriteEventArgs(value=b'\x01\x06')
[2023-09-27 10:13:17,324] [/dev/cu.usbmodemD3DAC88AD6C42_Event] [blatann.gatt.gatts.notify:94] [ERROR]: 'NoneType' object has no attribute 'sequence_number'
Traceback (most recent call last):
 File "blatann/event_type.py", line 90, in notify
 File "blatann/services/glucose/service.py", line 128, in _on_racp_write
 File "blatann/services/glucose/service.py", line 90, in _on_report_records_request
 File "blatann/services/glucose/service.py", line 90, in <lambda>
AttributeError: 'NoneType' object has no attribute 'sequence_number'
```
### Potential Cause
The issue seems to come from this test, which at first sight is here to cover the scenario where the database is empty:
https://github.com/ThomasGerstenberg/blatann/blob/983329ad023b5f6ff68fc3a8321340bc2370bf8d/blatann/services/glucose/service.py#L86

The `records` in this scenario is a list with one element (`None`):
https://github.com/ThomasGerstenberg/blatann/blob/983329ad023b5f6ff68fc3a8321340bc2370bf8d/blatann/services/glucose/service.py#L78
### Suggested solution

I think the expected behaviour would be that the `records` list is empty whenever the last or first record is requested (if the database does not contain any record).

Maybe something along the lines of `records = [record] if record else []`?

**Comment by ThomasGerstenberg** [comment]
That makes sense to me, good find!

**Comment by snap40ben** [comment]
Thanks!
